(function (root, factory) { if (typeof module === 'object' && module.exports) module.exports = factory(); else root.V10ActionDraft = factory(); }(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  function createActionDraft(deps) { deps = deps || {}; var roles = deps.roles, audit = deps.audit, drafts = {};
    function sync(d){if(d&&d.id)drafts[d.id]=d;return d;}
    function log(d, c, action, before, after, result, extra) { if (audit) audit.recordAudit(Object.assign({ taskId:d && d.taskId, action:action, operator:c&&c.operator, role:c&&c.role, beforeStatus:before, afterStatus:after, evidenceIds:d&&d.evidenceIds, result:result, context:c }, extra||{})); }
    function deny(d,c,action,error,reason) { log(d,c,action,d&&d.status,d&&d.status,'denied',{error:error,reason:reason}); return {ok:false,error:error,action:action,role:c&&c.role,reason:reason}; }
    function auth(d,c,a){var r=roles.assertAuthorized(c&&c.role,a); return r.ok?null:deny(d,c,a,r.error,'permission_denied');}
    function createDraft(o){o=o||{};if(!o.taskId)throw new Error('taskId is required');if((o.evidenceIds||[]).some(function(e){return typeof e!=='string'||e.indexOf('EV-')!==0;}))throw new Error('evidenceIds must start with EV-'); var now=new Date().toISOString(); var d={id:o.id||'draft-'+Math.random().toString(36).slice(2),taskId:o.taskId,title:o.title||'Action draft',target:o.target,suggestedActions:o.suggestedActions||[],diff:Object.assign({before:{},after:{},demonstrative:true},o.diff||{}),successMetrics:o.successMetrics||[],stopRollbackConditions:o.stopRollbackConditions||[],risks:o.risks||[],evidenceIds:o.evidenceIds||[],ownerRole:'optimizer',tenantId:o.tenantId||(o.context&&o.context.tenantId),createdAt:now,updatedAt:now,version:1,status:'draft',diagnosisConfirmed:false,degradation:null};return sync(d);}
    function transition(d,c,a,from,to){var x=auth(d,c,a);if(x)return x;if(d.status!==from)return {ok:false,error:'INVALID_TRANSITION',from:d.status,to:to};d.status=to;d.updatedAt=new Date().toISOString();sync(d);log(d,c,a,from,to,'success');return {ok:true,draft:d};}
    function confirmDiagnosis(d,c,o){o=o||{};var x=auth(d,c,'confirm_diagnosis');if(x)return x;if(o.status&&o.status!=='normal') {d.degradation=o;log(d,c,'confirm_diagnosis',d.status,d.status,'degraded',{reason:o.status});return {ok:false,error:'DEGRADED',result:'degraded',degradation:o};}if(!d.evidenceIds.length||d.evidenceIds.some(function(e){return typeof e!=='string'||e.indexOf('EV-')!==0;})) return deny(d,c,'confirm_diagnosis','INVALID_EVIDENCE','evidence_required');d.diagnosisConfirmed=true;log(d,c,'confirm_diagnosis',d.status,d.status,'success');return {ok:true,draft:d};}
    function submitDraft(d,c){var x=auth(d,c,'submit_draft');if(x)return x;if(!d.diagnosisConfirmed||!d.evidenceIds.length||d.evidenceIds.some(function(e){return e.indexOf('EV-')!==0;})||!d.target||!d.diff||!d.successMetrics.length||!d.stopRollbackConditions.length)return deny(d,c,'submit_draft','DEGRADED','required_fields_or_evidence');return transition(d,c,'submit_draft','draft','pending_approval');}
    function editDraft(d,c,o){o=o||{};var x=auth(d,c,'edit_draft');if(x)return x;if(d.status!=='draft'&&d.status!=='rejected')return {ok:false,error:'INVALID_TRANSITION',from:d.status,to:'draft'};if(o.expectedVersion!==undefined&&o.expectedVersion!==d.version)return deny(d,c,'edit_draft','STALE_VERSION','stale_version');Object.assign(d,o.patch||{});d.version++;d.status='draft';d.updatedAt=new Date().toISOString();sync(d);log(d,c,'edit_draft',d.status,'draft','success');return {ok:true,draft:d};}
    function approve(d,c){return transition(d,c,'approve','pending_approval','approved');} function reject(d,c,reason){var x=transition(d,c,'reject','pending_approval','rejected');if(x.ok)d.rejectionReason=reason||'rejected';return x;}
    function recordExecution(d,c,details){var x=transition(d,c,'record_execution','approved','execution_recorded');if(x.ok)d.execution=Object.assign({simulated:true,operator:c.operator},details||{});return x;}
    function observe(d,c){if(d.status!=='execution_recorded')return {ok:false,error:'INVALID_TRANSITION',from:d.status,to:'observing'};var old=d.status;d.status='observing';d.updatedAt=new Date().toISOString();sync(d);log(d,c,'observe',old,'observing','success');return {ok:true,draft:d};} function review(d,c){var x=auth(d,c,'view_review');if(x)return x;if(d.status!=='observing')return {ok:false,error:'INVALID_TRANSITION',from:d.status,to:'reviewed'};var old=d.status;d.status='reviewed';d.updatedAt=new Date().toISOString();sync(d);log(d,c,'review',old,'reviewed','success');return {ok:true,draft:d};} function close(d,c){if(d.status!=='reviewed')return {ok:false,error:'INVALID_TRANSITION',from:d.status,to:'closed'};var old=d.status;d.status='closed';d.updatedAt=new Date().toISOString();sync(d);log(d,c,'close',old,'closed','success');return {ok:true,draft:d};}
    function getAllDrafts(){return Object.keys(drafts).map(function(id){return drafts[id];});} function getDraft(taskId){var x=getAllDrafts().filter(function(d){return d.taskId===taskId;}).sort(function(a,b){return new Date(b.updatedAt)-new Date(a.updatedAt);});return x[0]||null;} function countByStatus(){var o={draft:0,pending_approval:0,approved:0,rejected:0,execution_recorded:0,observing:0,reviewed:0,closed:0};getAllDrafts().forEach(function(d){if(Object.prototype.hasOwnProperty.call(o,d.status))o[d.status]++;});return o;}
    return {createDraft:createDraft,confirmDiagnosis:confirmDiagnosis,submitDraft:submitDraft,editDraft:editDraft,approve:approve,reject:reject,recordExecution:recordExecution,observe:observe,review:review,close:close,getAllDrafts:getAllDrafts,getDraft:getDraft,countByStatus:countByStatus};
  } return {createActionDraft:createActionDraft};
}));
