'use strict';
const assert = require('assert');
const fs = require('fs'); const path = require('path');
const s = require('../security.js');
let passed = 0;
function test(name, fn) { try { fn(); passed++; console.log('  PASS ' + name); } catch (e) { console.log('  FAIL ' + name + ': ' + e.message); } }
const token = ['placeholder','token'].join('-');
const env = { STAGING_API_BASE_URL:'https://staging.example.test/api', STAGING_API_TOKEN:token, STAGING_PROVIDER_ID:'staging-v09', STAGING_PLATFORM:'synthetic', STAGING_HTTP_TIMEOUT_MS:'1000', STAGING_OVERALL_TIMEOUT_MS:'3000', STAGING_MAX_CONCURRENCY:'2', STAGING_RATE_LIMIT_RPS:'5', STAGING_MAX_RETRIES:'2' };
test('security/env-only-credentials', () => { const files = []; function walk(d) { for (const x of fs.readdirSync(d)) { const p=path.join(d,x); if (x==='node_modules'||x==='.git') continue; fs.statSync(p).isDirectory()?walk(p):files.push(p); } } walk(path.join(__dirname,'..','..')); const text=files.filter(x=>/\.(js|cjs|mjs|json|html)$/.test(x)).map(x=>fs.readFileSync(x,'utf8')).join('\n'); assert.ok(!text.includes(token)); assert.ok(s.ENV_NAMES.includes('STAGING_API_TOKEN')); });
test('security/base-url-allowlist', () => { assert.throws(()=>s.validateBaseUrl('http://staging.example.test',['staging.example.test']), /HTTPS/); assert.throws(()=>s.validateBaseUrl('https://evil.test',['staging.example.test']), /approved/); assert.throws(()=>s.validateBaseUrl('https://u:p@staging.example.test',['staging.example.test']), /credentials/); assert.strictEqual(s.readCredentials(env,{approvedHosts:['staging.example.test']}).token,token); });
test('security/read-scope-enforced', () => { assert.doesNotThrow(()=>s.requireCurrentRta({rtaId:'rta-1',dataScope:'current_rta_only',timeRange:{start:'2026-01-01',end:'2026-01-02'}})); assert.throws(()=>s.requireCurrentRta({rtaId:'rta-1',rtaIds:['rta-2'],dataScope:'current_rta_only',timeRange:{start:'a',end:'b'}}), e=>e.code==='INVALID_REQUEST'); assert.throws(()=>s.requireCurrentRta({rtaId:'rta-1',method:'POST',dataScope:'current_rta_only',timeRange:{start:'a',end:'b'}}), e=>e.code==='PERMISSION_DENIED'); });
test('security/masking-identifiers', () => { const x=s.maskObject({accountId:'abcdef12',accountName:'Brand',operator:'alice',phone:'13800138000',campaignName:'Secret',dailyBudget:1234,bidUrl:'https://x.test/p?q=secret',Authorization:token,nested:{IMEI:'123456'}}); assert.strictEqual(x.accountId,'ab****12'); assert.strictEqual(x.accountName,'[MASKED_ACCOUNT]'); assert.ok(!JSON.stringify(x).includes('13800138000')); assert.ok(!x.Authorization && x.nested.IMEI !== '123456'); assert.strictEqual(x.bidUrl,'https://x.test/p'); });
test('security/secrets-never-logged', () => { const x=s.maskObject({authorization:'x',token:'y',secret_key:'z',cookie:'c',signature:'sig',safe:'unknown'}); assert.deepStrictEqual(x,{}); const r=s.rotationRecord({rotatedBy:'ops',token,scope:'read',validation:'ok'}); assert.ok(!JSON.stringify(r).includes(token)); });
test('security/auth-permission-no-retry', () => { assert.deepStrictEqual(s.authOutcome(401),{code:'AUTH_REQUIRED',retryable:false}); assert.deepStrictEqual(s.authOutcome(403),{code:'PERMISSION_DENIED',retryable:false}); });
module.exports = { run: async () => passed === 6 ? 0 : 1 };
